lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Hey ! Please review and let me know what you think!

Make beaker-docker work in a docker container

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

The port mapping is for port 22 that is used to ssh. This maps a static random 4 digit port when the container is created so a random port is not assigned. 
When a random port is assigned it would change it when the container is restarted and beaker would still be using old port and would not be able to ssh.

(BKR-1189) Fix port mapping

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

As pointed out [here](https://github.com/puppetlabs/beaker-docker/pull/3#discussion_r135492133), PR #3 introduced a regression by setting the container name to the node hostname by default. This prevents running beaker concurrently with other beaker nodesets containing nodes with the same hostname.
This patch simply leaves that option blank by default (pre-PR3 behavior).

Don't set container name to node hostname

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

This adds support for archlinux, which is present [in beaker-puppet](https://github.com/puppetlabs/beaker-puppet/blob/master/lib/beaker-puppet/install_utils/foss_utils.rb#L285), originally introduced by pre-refactor [beaker PR 1289](https://github.com/puppetlabs/beaker/pull/1289) by @petems and I, but isn't supported for Docker.
This also introduces support for a ``docker_cap_add`` Array section of the config, which allows setting additional kernel capabilities for the SUT container (see [Docker kernel capabilities](https://docs.docker.com/engine/security/security/#linux-kernel-capabilities), [docker run --cap-add](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). This was needed for a module I'm testing; see below for more.
This should add the …

[BKR-1021] Archlinux support

---

lib/beaker/hypervisor/docker.rb

This fixes a few issues with the official archlinux docker images. The used nodeset:
```yaml
---
HOSTS:
archlinux-current-x64:
platform: archlinux-current-amd64
hypervisor: docker
image: archlinux/base
docker_preserve_image: true
docker_cmd: '["/bin/init"]'
docker_image_commands:
- 'pacman --noconfirm -Sy systemd-sysvcompat'
- 'systemctl mask getty@tty1.service getty-static.service'
- 'locale-gen en_US.UTF-8'
- 'echo LANG=en_US.UTF-8 > /etc/locale.conf'
CONFIG:
trace_limit: 200
masterless: true
```
The individual commits contain detailed information about the issues.

Fix Archlinux support

---

acceptance/config/nodes/hosts.yaml
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Allows custom docker options to be set via the container options JSON. Node set wide options can be set under the `config` hash using the `dockeropts` hash. Per host options can be set in each host using the `dockeropts` hash. Per host options override node set options. The `dockeropts` hash is copied into the container options.
An example of an option is `Labels`. A hash can be used to set any number of labels for the containers. For example, to target a specific Docker Swarm collection.

(BKR-305) Support custom docker options

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Prior to this commit, a user could choose between running from their own
custom entrypoint or running from the default ssh CMD. This made it
probelmatic for users wanting to use the default entrypoint for on image
while also having ssh running in the container.
This change allows a user to set 'use_image_entry_point' for a host;
this will use the image's own default CMD and load ssh after the image
has started, so that Beaker's DSL can still communicate with the
container.

(PUP-9212) Allow for image entry point CMDs

---

Gemfile
docker.md
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Before this commit, beaker-docker would copy the file contents of a
supplied dockerfile and use that to generate a new image. This had the
drawback of not being able to use much of the Dockerfile DSL, such as
COPY or VOLUME, because they were relative paths that were not copied
along with the Dockerfile itself.
This commit changes it so that a dockerfile is copied along with the
context of the test execution directory, so that those Dockerfile DSL
methods are usable with a Dockerfile used by beaker.

(PUP-9212) Allow for building containers with context

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Beaker 4's [subcommands](https://github.com/puppetlabs/beaker/blob/master/docs/tutorials/subcommands.md) significantly change how hypervisor methods are called during test runs. Instead of performing the full run with one command, the workflow now looks more like this:
- Run `beaker init --hosts=<hosts-file>` - this creates a `.beaker` folder that contains `subcommand_options.yaml`. This subcommand options file preserves state over the course of subsequent subcommands
- Run `beaker provision`. This creates the SUTs requested in the hosts file, but does not run any tests.
- Run `beaker exec <tests-or-suites>` to run the tests on the SUTs. Repeat if needed.
- Run `beaker destroy` to destroy the SUTs. 
Previously, beaker-docker used `host` objects to store several types of ruby objects for …

(BKR-1551) Updates for Beaker 4

---

lib/beaker/hypervisor/docker.rb

MaxAuthTries is set too low for users with large keyrings to be able to
successfully execute tests on a local system.

Allow users with large keyrings to run test

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

As per https://tickets.puppetlabs.com/browse/BKR-1586 this change allows a new flag to be defined for the docker hypervisor ```use_image_as_is``` which will cause the *provision* step of the process to simply pull the image down and use it without rebuilding it.
This pushes the responsibility for setting up a root:root ssh process on the container onto the user but has the benefit of speeding up test time by only having to do a ```docker pull``` rather than a ```docker build```

BKR-1586 - allow an 'as-is' container to be used rather than rebuilding every time

---

lib/beaker/hypervisor/docker.rb

See individual commits for more details
Related to https://github.com/puppetlabs/beaker-puppet/pull/117

(maint) A number of fixes for rerunning tests on docker containers

---

lib/beaker/hypervisor/docker.rb

By default ssh will try all keys stoered in the ssh agent when
connecting to a server.  If a agent has many keyes loaded it can leed to
the server responding with the following error before the
username/password pair is tried:
Net::SSH::Disconnect - disconnected: Too many authentication failures
This PR updates the ssh config to use :keys_only which translates to the
ssh confi IdentitiesOnly

Fix: Too many authentication failures

---

beaker-docker.gemspec

docker-api 2.0.0 removes the validate_version function used here:
lib/beaker/hypervisor/docker.rb

Fix: docker-api gem dependency

---

.github/workflows/test.yml
Rakefile

The original testing command in Jenkins was
`bundle exec rspec -fd -c spec`.
This changes moves testing to use the defined tests
in the Rakefile and runs those tests in GH Actions

Move testing to GH Actions

---

README.md
acceptance/config/nodes/hosts.yaml
beaker-docker.gemspec
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

* Fixed
* Validated support for podman in root and rootless mode
* Requires swipely/docker-api#569
* Changed the acceptance nodesets to centos so that testing on both
podman and docker will function properly
* No longer start containers in privileged mode by default for safety
reasons
* Updated the README
* Fixed support for connections to socket files
* Added a check for detection of SSH ports < 1024 if operating in
rootless mode
* Ensure that the IP is set to 127.0.0.1 instead of 0.0.0.0 for better
SSH connections
* Override host.reboot so that containers are not accidentally
destroyed
* Fixed PAM session entries due to known pam_loginuid issues
* Override enable_root_login since it is already performed by
this plugin
* Override ssh_service retart if the init process is set as sshd …

Add Podman Support

---

.github/workflows/test.yml
Gemfile.local
Rakefile
acceptance/config/nodes/hosts.yaml
acceptance/tests/00_default_spec.rb
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

* Ensure that docker is fully functional with the new changes
* Determined that docker, unlike podman, only assigns the host IP
after the instance has been created
* Updated the GitHub Actions to test both podman and docker
* Used a simple acceptance test for validation since the upstream beaker
tests are wired for Vagrant
* Fail if the container is in an inaccessible state instead of trying to
SSH forever

Fix docker support and update github actions

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Privileged cannot be set if the user selects individual CAPs to set.
However, to preserve legacy runner compatibiliy, privileged should be
set if neither is set.

Deconflict Privileged and CAPs

---

README.md
beaker-docker.gemspec

Emails were removed from the gemspec because they are no longer valid
addresses. The author names were preserved to represent those who have
put lots of work into this.
Other items were updated to reflect that this gem was recently dontated
to Vox Pupuli and to account for recent PRs.

Cleanup docs and gemspec

---

Gemfile.local
beaker-docker.gemspec
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Fixed the 'rootless' port check to use the new `::Docker.rootless?`
instead of checking the current UID since that was prone to false
positives.

Update to Check Rootless

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

This fixes #43 .  Output from local docker run of beaker using this patch:
```
centos-7 15:07:30$ cat /etc/resolv.conf
Attempting ssh connection to 127.0.0.1, user: root, opts: {:password=>"root", :port=>"5484", :forward_agent=>false, :auth_methods=>["password", "publickey", "hostbased", "keyboard-interactive"]}
```
Before this patch my local executions using beaker were trying to connect to the container IP and port 22 both of which won't work.

Fix docker usage to use correct port and IP address on local docker

---

lib/beaker/hypervisor/docker.rb

Added the `force` option whenever a container is to be deleted so that
random potential errors don't fail the run.

Force Container Removal

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Fedora has defaulted to chrony since Fedora 14. It also uses DNF by default since Fedora 22. Both of these are also true for EL8. While this doesn't use chrony on Fedora 14-21, it doesn't really matter since those are EOL for a long time now.

Treat Fedora 22+ and EL8 the same

---

docker.md
lib/beaker/hypervisor/docker.rb

This fixes #46 for my docker-in-docker gitlab runner setup.

Added ENV DOCKER_IN_DOCKER to fix SSH conn info

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Fixes #52 
From what I can gather the key lookup of `PortBinding` in network settings is wrong, but rather than assume it never exists, I kept behavior but if `Ports` exists, which is used in unit tests and what my Docker daemon exposes, then use that instead.
So unit tests look like what I see on my Docker daemon:
```json
"NetworkSettings": {
"Bridge": "",
"SandboxID": "5b3ed04c8e2e65b854bd9a05cf2053e0ae4e932e3e43811197a10255e646ad40",
"HairpinMode": false,
"LinkLocalIPv6Address": "",
"LinkLocalIPv6PrefixLen": 0,
"Ports": {
"22/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "4584"
}
]
},
"SandboxKey": "/var/run/docker/netns/5b3ed04c8e2e",
"SecondaryIPAddresses": null,
"SecondaryIPv6Addresses": null,
"EndpointID": "ee4961d5a4a1b37548b6c24b3b1be1ee0473a4d9057b0502c6ebe4ebf2129d1c",
"Gateway": …
```

Fix SSH port binding

---

beaker-docker.gemspec
lib/beaker/hypervisor/docker.rb

This new method determines the packages to install while taking the host into account. This means docker and non-docker follow the same logic.

Use host_packages helper to reuse logic from beaker

---

Gemfile

we already pull it in via beaker-docker.gemspec.

Remove beaker from Gemfile

---

docker.md
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Adds a Docker hostfile parameter `docker_image_first_commands` which allows inserting RUN commands at the very top of the Dockerfile. This allows proxy configuration for apt/yum/dnf.
`docker_image_commands` does not work for this as it's commands are inserted too late to configure proxy for all package manager commands. 
Thank you for considering. I am behind a proxy at my company and this makes testing a bit easier for me as we don't currently have a direct-to-internet environment for development.

Add Docker hostfile parameter docker_image_first_commands

---

lib/beaker/hypervisor/docker.rb

This creates keys for all the supported types.

Use ssh-keygen -A on modern Enterprise Linux

---

lib/beaker/hypervisor/docker.rb

It was possible to generate a ssh port <= 1024 before. This is ok for rootful containers but it doesn't work for rootless. That causes another re-provisioning attempt until the port above 1024 is generated. With this change the generated port is always within 1025..9999 inclusive range.

Generate a ssh port from 1025..9999 range

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Changes:
* Reduce layers amount in the image generated from the built-in Dockerilfe (every RUN produces another layer)
* Squash multiple sed invocations into one
* Sync sshd_config changes in the built-in Dockerfile and in the fix_ssh() function.
* Improve ssh service name detection in fix_ssh()
* Implement some rubocop suggestions
* Remove unused sshd_options variable

Refactor built-in Dockerfile and fix_ssh()

---

.rubocop_todo.yml
Rakefile
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

This is dropped in Ruby 3.2 and RuboCop also flags it as a potential performance improvement.

Deal with docker_cmd being an array and remove use of =~

---

lib/beaker/hypervisor/docker.rb

This is present in at least EL7 and we don't test on older versions
anymore. The benefit is that keys for all supported types are generated.

Use ssh-keygen -A on Red Hat-based distros & SuSE/SLES

---

lib/beaker/hypervisor/docker.rb

This saves a few redundant variable assignments.

Simplify port detection code

---

beaker-docker.gemspec

We still need to allow version < 1.9 for Ruby < 2.7 support.

Allow fakefs 2.x

---

beaker-docker.gemspec
spec/spec_helper.rb

Includes https://github.com/voxpupuli/beaker-docker/pull/97 to avoid a merge conflict later on.

Remove unused rspec-its dependency

---

.editorconfig
.gitignore
.rubocop.yml
.rubocop_todo.yml
.simplecov
Gemfile
Gemfile.local
Rakefile
acceptance/tests/00_default_spec.rb
beaker-docker.gemspec
bin/beaker-docker
lib/beaker-docker.rb
lib/beaker-docker/version.rb
lib/beaker/hypervisor/docker.rb
spec/spec_helper.rb

This PR includes rubocop-inspired fixes. Though there was few unrelated changes:
- `Gemfile.local` was removed
- `vendor` directory was added to the `.gitignore`
- `.editorconfig` added (mostly to keep trailing spaces and newlines under control)
- `bin/beaker-docker` was fixed (it seems it was never really working 🤔)
- `00_default_spec.rb` was rewritten in Beaker DSL (`beaker-rspec` was not really used there)

Fix rubocop-related issues (part 1)

---

.rubocop.yml
Gemfile
Gemfile.local

A local file checked into git is contradictory. This merges the file into Gemfile.

Remove Gemfile.local from git

---

bin/beaker-docker

This allows running:
beaker-docker containerfile centos9-64
The spec is ran through beaker-hostgenerator and then it writes to Containerfile. The filename can also be passed in as an additional argument.
This is an alternative to https://github.com/voxpupuli/beaker-docker/pull/124.

Implement writing out a containerfile for a host

---

Rakefile

our metagem voxpupuli-rubocop defines the rake task, we don't need to do it on our own.

Rakefile: Use rubocop tasks from voxpupuli-rubocop

---

acceptance/config/nodes/hosts.yaml
beaker-docker.gemspec

also contains https://github.com/voxpupuli/beaker-docker/pull/139
This is required because the old images are EoL and not working anymore.

CI: Switch from EL7/8->Debian12/EL9

---

beaker-docker.gemspec

2.2 and older allowed latest excon releases. excon v0.111.0 introduced a frozen string that was incompatible with docker-api 2.2 and older. This was fixed in https://github.com/upserve/docker-api/pull/588. Bumping our dependency to docker-api 2.3 or newer ensures that we don't pull in broken versions by accident.

docker-api: depend on 2.3 or newer

---

lib/beaker/hypervisor/docker.rb

beaker already does this:
https://github.com/voxpupuli/beaker/blob/8bcd67c3216b99a9d8a88764c1d377702a1349c1/lib/beaker/host/unix/pkg.rb#L73C7-L80

Arch Linux: remove redundant system updates

---

lib/beaker/hypervisor/container.rb
lib/beaker/hypervisor/container_podman.rb

This allows us to set the beaker hypervisor not only to `docker`, but also to `docker_podman`. This enables us to implement podman specific patches (if we ever need to). But it also makes it easier for modules to specify if they want to use podman or docker. See https://github.com/voxpupuli/gha-puppet/pull/48 for reference.

Add ContainerPodman class

---

lib/beaker/hypervisor/container_docker.rb
lib/beaker/hypervisor/container_swarm.rb

both are plain aliases for Container, which is an alias for Docker
(today), as that's where all the code lives

add ContainerDocker and ContainerSwarm

---

lib/beaker/hypervisor/docker.rb

There are 2 related changes:
1. UsePAM is now disabled everywhere. It causes some hard to debug problems on CentOS9 and Fedora containers, when running on Ubuntu 24.04 host. It's somehow related to user namespaces, AppArmor and pam_unix (/etc/shadow access).
2. As more and more distros adopts /etc/ssh/sshd_config.d directory for ssh configs, now Dockerfile overrides settings in those files as well.

Update sshd configuration (UsePAM no, sshd_config.d)

---

lib/beaker/hypervisor/docker.rb

compgen is a builtin command, so should be everywhere

fix: ignore /etc/ssh/sshd_config.d/* if files are not present
